// Auto-generated by tools/build.py — do not edit app/sw.js by hand.
const VERSION = 'fa5f71eaf8';
const CACHE = 'zitie-' + VERSION;
const PRECACHE = [
 "./",
 "./app.js",
 "./config.js",
 "./data/strokes.json",
 "./data/zitie-data.json",
 "./fonts/LXGWWenKaiGB-subset.woff2",
 "./fonts/ZitieFang-subset.woff2",
 "./fonts/ZitieHei-subset.woff2",
 "./fonts/ZitieSong-subset.woff2",
 "./icons/apple-touch-icon.png",
 "./icons/icon-192.png",
 "./icons/icon-512.png",
 "./icons/icon-maskable-512.png",
 "./index.html",
 "./licenses/LXGWWenKaiGB-OFL.txt",
 "./licenses/ZitieFang-OFL.txt",
 "./licenses/ZitieHei-OFL.txt",
 "./licenses/ZitieSong-OFL.txt",
 "./licenses/hanzi-writer-data-ARPHICPL.TXT",
 "./manifest.json",
 "./style.css"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('zitie-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request).catch(() => caches.match('./index.html')))
  );
});
